/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.CRT_CATEGORIA;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.CATEGORIA;

/**
 *
 * @author cesar
 */
public class InternalJframeCategoria extends javax.swing.JInternalFrame {

    public InternalJframeCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        labelWalppaper = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Nueva Categoria");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setText("Descripcion categoria:");
        getContentPane().add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 150, -1));

        botonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 120, -1));

        labelWalppaper.setForeground(new java.awt.Color(255, 255, 255));
        labelWalppaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(labelWalppaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        CATEGORIA categoria = new CATEGORIA();

        CRT_CATEGORIA controlCategoria = new CRT_CATEGORIA();

        categoria.setDescripcion(txtDescripcion.getText().trim());
        categoria.setEstado(1);

        if (txtDescripcion.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "complete todos los campos");

        } else {

            if (!controlCategoria.CategoriaExistente(txtDescripcion.getText().trim())) {

                categoria.setDescripcion(txtDescripcion.getText().trim());
                categoria.setEstado(1);

                if (controlCategoria.GUARDAR(categoria)) {

                    JOptionPane.showMessageDialog(null, "Registro guardado");

                } else {
                    JOptionPane.showMessageDialog(null, "La categoria que desea agregar ya existe");
                }

            } else {

                JOptionPane.showMessageDialog(null, "La categoria que desea agregar ya existe");

            }

        }

        txtDescripcion.setText("");


    }//GEN-LAST:event_botonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelWalppaper;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
