package vista;

import Conexcion.conexion;
import controlador.CRT_PRODUCTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.PRODUCTO;

/**
 *
 * @author cesar
 */
public class MenuInterProductos extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCombox = 0;

    public MenuInterProductos() {
        initComponents();
        this.setSize(new Dimension(400, 400));
        this.setTitle("Productos");

        this.CargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        ComboIVA = new javax.swing.JComboBox<>();
        comboCategorias = new javax.swing.JComboBox<>();
        Boton_GuardarProducto = new javax.swing.JButton();
        labelWallpaper = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IVA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categorias:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 210, -1));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, -1));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 210, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, -1));

        ComboIVA.setBackground(new java.awt.Color(255, 255, 255));
        ComboIVA.setForeground(new java.awt.Color(0, 0, 0));
        ComboIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona IVA", "No grava IVA", "12%", "14%" }));
        ComboIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboIVAActionPerformed(evt);
            }
        });
        getContentPane().add(ComboIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 210, -1));

        comboCategorias.setBackground(new java.awt.Color(255, 255, 255));
        comboCategorias.setForeground(new java.awt.Color(0, 0, 0));
        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona categoria" }));
        getContentPane().add(comboCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, -1));

        Boton_GuardarProducto.setBackground(new java.awt.Color(0, 204, 153));
        Boton_GuardarProducto.setForeground(new java.awt.Color(255, 255, 255));
        Boton_GuardarProducto.setText("Guardar");
        Boton_GuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_GuardarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_GuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        labelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(labelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboIVAActionPerformed

    private void Boton_GuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarProductoActionPerformed
        // TODO add your handling code here:

        PRODUCTO producto = new PRODUCTO();
        CRT_PRODUCTO controlProducto = new CRT_PRODUCTO();
        String IVA = "";
        String categoria = "";
        IVA = ComboIVA.getSelectedItem().toString().trim();
        categoria = comboCategorias.getSelectedItem().toString().trim();

        if (txtNombre.getText().equals("") || txtCantidad.getText().equals("") || txtPrecio.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Complete todos los items");
            txtNombre.setBackground(Color.red);
            txtCantidad.setBackground(Color.red);
            txtDescripcion.setBackground(Color.red);
            txtPrecio.setBackground(Color.red);

        } else {

            if (!controlProducto.ProductoExistente(txtNombre.getText().trim())) {

                if (IVA.equalsIgnoreCase("Selecciona IVA")) {

                    JOptionPane.showMessageDialog(null, "Seleccione IVA");

                } else {

                    if (categoria.equals("Seleccione la categoria: ")) {

                        JOptionPane.showMessageDialog(null, "SSelecciona categoria");

                    } else {

                        try {

                            producto.setNombre(txtNombre.getText().trim());
                            producto.setCantidad(Integer.parseInt(txtCantidad.getText().trim()));
                            String precioTXT = "";
                            double precio = 0.0;
                            precioTXT = txtPrecio.getText().trim();
                            boolean aux = false;

                            for (int i = 0; i < precioTXT.length(); i++) {

                                if (precioTXT.charAt(i) == ',') {

                                    String precioNuevo = precioTXT.replace(",", ".");
                                    precio = Double.parseDouble(precioNuevo);
                                    aux = true;

                                }

                            }

                            if (aux == true) {

                                producto.setPrecio(precio);

                            } else {

                                precio = Double.parseDouble(precioTXT);
                                producto.setPrecio(precio);

                            }

                            producto.setDescripcion(txtDescripcion.getText().trim());

                            if (IVA.equalsIgnoreCase("No grava iva")) {
                                producto.setPorcentajeIVA(0);

                            } else if (IVA.equalsIgnoreCase("12%")) {

                                producto.setPorcentajeIVA(12);
                            } else if (IVA.equalsIgnoreCase("14%")) {
                                producto.setPorcentajeIVA(14);
                            }

                            this.ID_CATEGORIA();
                            producto.setIdCategoria(obtenerIdCategoriaCombox);
                            producto.setEstado(1);

                            if (controlProducto.GUARDAR(producto)) {

                                JOptionPane.showMessageDialog(null, "Registro guardado");
                                txtNombre.setBackground(Color.green);
                                txtCantidad.setBackground(Color.green);
                                txtPrecio.setBackground(Color.green);
                                txtDescripcion.setBackground(Color.green);

                                this.CargarCategorias();
                                this.ComboIVA.setSelectedItem("Seleccione IVA");
                                this.limpiar();

                            } else {
                                JOptionPane.showMessageDialog(null, "Error en el registro guardado");

                            }

                        } catch (HeadlessException | NumberFormatException e) {

                            JOptionPane.showMessageDialog(null, "error");

                        }

                    }

                }

            } else {

                JOptionPane.showMessageDialog(null, "El producto ya existe en la base de datos, no se puede agregar denuevo");

            }

        }


    }//GEN-LAST:event_Boton_GuardarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_GuardarProducto;
    private javax.swing.JComboBox<String> ComboIVA;
    private javax.swing.JComboBox<String> comboCategorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelWallpaper;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        txtNombre.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");

    }

    private void CargarCategorias() {

        Connection cn = conexion.conectar();
        String sql = "SELECT * FROM CATEGORIA";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            comboCategorias.removeAllItems();
            comboCategorias.addItem("Seleccione la categoria");
            while (rs.next()) {

                comboCategorias.addItem(rs.getString("Descripcion"));
            }

            cn.close();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error al cargar las categorias");

        }

    }

    private int ID_CATEGORIA() {
        String sql = "SELECT * FROM CATEGORIA WHERE Descripcion ='" + this.comboCategorias.getSelectedItem() + "'";

        Statement st;

        try {

            Connection cn = conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                obtenerIdCategoriaCombox = rs.getInt("ID_Categoria");

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error con el id de la categoria ");

        }

        return obtenerIdCategoriaCombox;

    }

}
